#!/bin/sh

first_line=$(head -n 1 "$1")

if echo "$first_line" | grep -Eq '^(feat|fix|docs|style|refactor|perf|test|chore|build|ci)(\([[:alnum:]_-]+\))?!?: '; then
  exit 0
fi

sed -i.bak -e '1s/^/chore: /' "$1"
rm -f "$1.bak"
